@startuml ErDiagram

skinparam linetype ortho

entity Users {
  *id : number <<generated>>
  --
  *email : string
  *passwordHash : string
  firstName : string
  lastName : string
}

entity Houses {
  *id : number <<generated>>
  --
  address : string
}

entity HouseOwners {
  *id : number <<generated>>
  --
  *homeId : number <<FK>>
  *ownerId : number <<FK>>
}

entity Devices {
  *id : id <<generated>>
  --
  *homeId : number <<FK>>
  type : int
  connect_url : string
  status : string
}

entity Scenarios {
  *uuid : UUID <<generated>>
  --
  *home_uuid : UUID <<FK>>
  scenario : string
  cron : string
}

Users ||..o{ HouseOwners
Houses ||..o{ Scenarios
Houses ||..o{ HouseOwners
Houses ||..o{ Devices

@enduml